post_it_gen/urls.py
from django.conf.urls import patterns, url
from post_it_gen import views

# This is the file where URLs are matched with views using regular expression. 
# @author Tushar Bhargava

urlpatterns = patterns('',
    # This regular expression matches to the homepage 
    url(r'^$', views.the_wall, name='home_page'),
    url(r'^submit/',views.submit, name="submit"),
)

the_rejection_wall/urls.py
from django.conf.urls import patterns, include, url
from post_it_gen import views
from django.contrib import admin
admin.autodiscover()

# In this file we simply include the URL handlers defined in the 'post-it' sub-app.

urlpatterns = patterns('',
   
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('post_it_gen.urls',namespace="post_it_gen")),
)

post_it_gen/models.py
from django.db import models
import random

# This stores my data model for the project, namely a 'PostIt' class that has color (randomized) and text content.
# @author Tushar Bhargava

# Almost like a constructor for the model
class PostItManager(models.Manager):
    def create_post_it(self):
        post_it=self.create()
        post_it.random_color_gen()
        return post_it

class PostIt(models.Model):
    content=models.CharField(max_length=400)
    color=models.CharField(max_length=200)
    objects=PostItManager()

    # This function randomly generates a color for the post it note (hexadecimal color code which we can feed to HTML)
    def random_color_gen(self):
        rand=lambda: random.randint(0,255)
        self.color='#%02X%02X%02X' % (rand(),rand(),rand())

    def set_content(self,content_val):
        self.content=content_val

    def __unicode__(self):
        return self.content

post_it_gen/views.py
from django.shortcuts import render
from django.http import HttpResponse
from post_it_gen.models import PostIt,PostItManager
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# This file stores all 'views' of the Django project. "A view in Python is a function that takes a Web request
# and returns a Web response." ~ From official documentation. 
# @author Tushar Bhargava

# The main view that shows the rejection wall (the home page so to speak) 
def the_wall(request):
    # Creating a 'context' which is basically this bundle of python that we link with the webpage to give it turbo powers.
    all_rejections=PostIt.objects.all()
    # Storing all the rejection post-its in the context
    context={'all_rejections':all_rejections}
    # Returning an HttpResponse object, which is the webpage linked with the context. 
    return render(request,'post_it_gen/index.html',context)

# This view handles submitting the post-it text for storage in the database. 
def submit(request):
    entered_content=request.POST['text_input_bar']
    post_it=PostIt.objects.create_post_it()
    post_it.set_content(entered_content)
    # Saving the post-it to the database
    post_it.save()
    return HttpResponseRedirect(reverse('post_it_gen:home_page'))

post_it_gen/templates/post_it_gen/index.html
<!DOCTYPE HTML>

<!-- 
	To Do list:

	1.) Adjust the post-it model to randomly generate positions within a range (overlap doesn't matter).
    2.) Make size of post-its slightly smaller
    3.) Make sure colors of PostIt are acceptable, specify range? (Optional) 
    4.) Password protected rejections -- using Open ID verifications (Advanced Optional)
	
-->

<html>
	<head>
		<title>
			The Rejection Wall 
		</title>
		
        <!-- Loading the static files (CSS, images, JS etc) -->
        {% load staticfiles %}

		<link rel="stylesheet" type="text/css" href="{% static 'post_it_gen/style.css' %}" />
		<!-- Google Fonts -->
		<link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
		<!-- Loading jQuery -->
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"> </script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
		<script type="text/javascript" src="{% static 'post_it_gen/script.js' %}"> </script>
		<!-- Put Favicon icon here.-->
		
	</head>
	
	<body>
		<h1>The Rejection Wall</h1>
		<h2>Been rejected? Pin it.</h2>
		<!-- We've defined a view to take care of the form, we can re-direct back to the home page after taking in the info -->
		<form id="text_input_form" action="{% url 'post_it_gen:submit' %}" method="post">
            <!-- To prevent cross-site request forgery we use the tag provided by Django. -->
            {% csrf_token %} 
			<input type="text" name="text_input_bar" placeholder="I was rejected by" id="text_input_bar">
			<input type="submit" name="submit_button" value="Pin it" id="submit_button_in_form">
		</form>

        <!-- Creating some space between form input and the post-its -->
        <div>
            <p></p>
            <p></p>
            <p></p>
        </div>		

        <!-- Now making post-its from our stored data. -->
      
            <!-- The context we passed the bundle had all the post-its!-->
            <!-- Trying to put a wrapper to get post-its to display. -->
            <ul class="wrapper">
            {% for post_it in all_rejections %}
                <li class="post-it-note" style="background-color:{{post_it.color}};">
                    <div class="pin"></div>
                    <p>{{post_it.content}}</p>
                </li>
            {% endfor %}
            </ul>

	</body>
	
</html>